CONTRIBUTING.md, commit-message-pr-style.md
=> contributing: add commit message and pr style

README.md
=> Fix expression mistakes of readme

soc/README.md
Add idea list for summer of code.
=> soc: Add idea list

soc/README.md
=> add two features in soc

soc/README.md
=> soc: refine wording and format

code-comment-style.md
@lilin90 @shenli @gingerkidney  PTAL Thanks.
=> Add code comment style

CONTRIBUTING.md
This PR will link to the comment style in the tikv repo.
It can only be merged when [tikv/tikv#4204](https://github.com/tikv/tikv/pull/4204) (waiting for Brian's review tomorrow) is merged.
=> CONTRIBUTING: add code comment style

code-comment-style.md
=> Update the format of Code Comment Style

commit-message-pr-style.md
=> Improve description and add commit message examples

committer.md
=> Creat Committer.md

contributors/command-help.md
=> contributors: add sre-bot command help doc

contributors/workflow.md
=> contributors: add how to cherry-pick a commit to the workflow

CONTRIBUTING.md
After this PR is merged, I'm going to update the `contributing.md` in the tidb repo to point to this document.
=> CONTRIBUTING.md: update this doc

working-groups/README.md, working-groups/wg-vec-expr.md
=> working group: add vectorized expression working group

special-interest-groups/sig-expr/roles-and-organization-management.md
Updated heading levels to be more logical
=> update heading levels

challenge-Programs/README-CN.md, challenge-Programs/performance-challenge-cn.md
=> fix some typos in performance-challenge-cn.md

challenge-Programs/performance-challenge-cn.md
* fix link of  "set up git"
@zz-jason @gingerkidney 
PTAL
=> fix link of  "set up git"

challenge-Programs/performance-challenge-cn.md
@zz-jason @gingerkidney 
PTAL~
=> add a note of sign up

challenge-Programs/README.md, challenge-Programs/performance-challenge.md
=> Add English description of "TiDB Performance Challenge Program"

challenge-Programs/performance-challenge-cn.md
* add a note of sign up
* add challenge rules of vectorization issue
@zz-jason @you06 PTAL
=> add challenge rules of vectorization issue

challenge-Programs/performance-challenge.md
- Add two pieces of description in Sign up
- Add one piece of description in Heads-up
=> challenge-programs: update the description in README-EN

challenge-Programs/performance-challenge.md
The two website URLs in Step 6 are wrong.
=> Change the website URL

challenge-Programs/performance-challenge-cn.md, challenge-Programs/performance-challenge.md
* change the link of tidb performance challenge website
@zz-jason @gingerkidney PTAL
=> change the link of website

working-groups/README.md, working-groups/wg-sql-diagnostics.md
Signed-off-by: Lonng <heng@lonng.org>
=> add wg-sql-diagnostics working group

working-groups/wg-sql-diagnostics.md
Signed-off-by: Lonng <heng@lonng.org>
=> add mentor to wg-sql-diagnostics

working-groups/README.md, working-groups/wg-key-visualizer.md
Signed-off-by: andylokandy <andylokandy@hotmail.com>
Implement a visual component to show key heatmap of the TiKV cluster, which is useful for troubleshooting and reasoning inefficient application usage patterns.
=> add working group `wg-key-visualizer`

working-groups/wg-key-visualizer.md
fix key visualizer working group format.
=> working-groups: fix wg-key-visualizer format

working-groups/README.md, working-groups/wg-wasm.md
Signed-off-by: lucklove <gnu.crazier@gmail.com>
=> Add TiDB Wasm Working Group

working-groups/README.md, working-groups/wg-dynamic-configuration-change.md
This PR adds the working group for the dynamic configuration change.
=> add working group `wg-dynamic-configuration-change`

working-groups/wg-key-visualizer.md
update key visualizer working group meeting notes link and agenda link
=> working-groups: update wg-key-visualizer

working-groups/wg-dynamic-configuration-change.md
This PR adds two members' information and the tracking issue for the working group.
=> working-groups: add two members and tracking issue

working-groups/README.md, working-groups/wg-test-infra.md
Add "Test Infra" working group.
=> working-groups: add test infra working group

working-groups/README.md, working-groups/wg-drainer-relay-log.md
Add drainer relay log working group.
=> working-groups: add drainer relay log working group

working-groups/README.md, working-groups/wg-dm-portal.md
=> working-groups: add dm-portal working group

architecture/contributor-list.md
Remove `can`  since it's inappropriate.
=> refine the contributor-list.md

working-groups/wg-dm-syncer.md
doc and rfc will be added in tomorrow.
=> a proposal for dm-syncer wg

working-groups/README.md, working-groups/wg-tidb-distributions.md
- Add "TiDB Distributions" working group
=> working-groups: add "TiDB Distributions" working group

governance/wg-governance.md
=> governance: reframe the working group governance

special-interest-groups/sig-ddl/member-list.md
=> SIG: fix typos

README.md
=> fix slack channel link

challenge-programs/challenge-program-season-2.md
This PR added english version of readme for UCP season 2.
=> challenge-programs: add description for UCP season 2

challenge-programs/challenge-program-season-2.md
=> challenge-programs: fix some formatting 

challenge-programs/README-CN.md, challenge-programs/challenge-program-season-2-cn.md
Add cherry-bot project, some easy tasks are ready.
=> challenge-programs: add cherry-bot project

challenge-programs/README-CN.md, challenge-programs/README.md, challenge-programs/challenge-program-season-2-cn.md, challenge-programs/challenge-program-season-2.md
Changed from
to:
to make it more clear.
Add TiDB Dashboard proposal submission links as below:
=> challenge program: unify projects

challenge-programs/README-CN.md, challenge-programs/README.md, challenge-programs/challenge-program-season-2-cn.md, challenge-programs/challenge-program-season-2.md
our challenge program s2 project dashboard: https://github.com/pingcap/tidb-operator/projects/4
=> challenge-programs: add tidb-operator challenge program s2 project

README.md, communicating.md
1. Added links to SIG list and WG list.
2. Fixed Challenge Program broken link.
3. Modified link titles to be clear about external resources or in-this-repo resources.
=> *: improve some links

challenge-programs/challenge-program-season-2.md
Updated in sync with https://github.com/pingcap/community/pull/182
=> update readme for season 2

challenge-programs/challenge-program-season-2.md
=> Update rules 

rfc/2020-04-13-discourse-theme-asktug.md
=> rfc: add discourse theme asktug into incubator programs

special-interest-groups/sig-docs/member-list.md
Update the sig-docs contributor list.
=> sig-docs: add new contributors

special-interest-groups/sig-docs/README.md
Update the link of joining #sig-docs Slack channel
=> sig: update #sig-docs Slack link

special-interest-groups/sig-ddl/README.md
=> sig: update #sig-ddl slack invitation link

special-interest-groups/README.md, special-interest-groups/sig-scheduling/README.md
Signed-off-by: nolouch <nolouch@gmail.com>
- update the channel link
- update the `README`
=> sig: update the link of sig-scheduling

special-interest-groups/sig-docs/roles-and-organization-management.md
Update the Slack link for sig-docs with referral.
=> sig-docs: update slack link for sig-docs

special-interest-groups/sig-docs/member-list.md
Update the contributor list of May 8th.
=> sig-docs: update contributor list

special-interest-groups/sig-dashboard/member-list.md
=> Add internal committers to Dashbaord SIG

special-interest-groups/sig-tiup/member-list.md
Signed-off-by: Lonng <heng@lonng.org>
=> tiup-sig: update the member informations

special-interest-groups/sig-exec/member-list.md
=> SIG: update sig-exec member list

special-interest-groups/sig-web/member-list.md
=> sig-web: update memeber-list

special-interest-groups/sig-ddl/member-list.md
Update the member list of DDL-SIG
=> special-interest-groups/sig-ddl: update the member-list of DDL-SIG

special-interest-groups/sig-template/README.md, special-interest-groups/sig-template/member-list.md, special-interest-groups/sig-web/member-list.md
This PR Update the template for sig
- README
- member-list
=>  special-interest-groups/sig-template: update the template

special-interest-groups/sig-docs/member-list.md
Update the Docs SIG member list.
=> sig-docs: update member list

contributors/figma-quick-start-guide.md
Alex has updated our diagram design templates. We need to use the new link address.
=> contributors: update the Figma link

special-interest-groups/sig-docs/member-list.md
Update the Docs SIG member list.
=> sig-docs: update Docs SIG member list

special-interest-groups/sig-tools/README.md, special-interest-groups/sig-tools/member-list.md
1. Included information of the regular meetings.
2. Updated member list to according to latest statistics
=> sig-tools: update meeting info and update member list

special-interest-groups/sig-ddl/README.md, special-interest-groups/sig-ddl/member-list.md, special-interest-groups/sig-ddl/roles-and-organization-management.md
- Add learning materials and code locations
- Update member-list and  roles-and-organization-management
=> special-interest-groups: update SIG-DDL

special-interest-groups/sig-exec/member-list.md
Contribution of lzmhhh123:
1. Realized index merge join.
2. Realized fast analyze.
3. Realized TiFlash access path in region cache.
and so on.
Contribution of winoros:
- Implemented the index join and did many improvement for it.
- Maintain the Reader executors
and so on.
=> sig: update the sig-exec member list

special-interest-groups/sig-exec/member-list.md
wjhuang2016: 20+ PRs of execution and expression component;
tiancaiamao: 30+ PRs and a co-author of table partitioning;
cfzjywxk: 50+ PRs
imtbkcat: 30+ PRs
=> SIG-ecec: update the member list

special-interest-groups/sig-tools/member-list.md
I am eligible for becoming a reviewer given that I fixed this issue https://github.com/pingcap/ticdc/issues/660
=> Nominate liuzix to be a reviewer in sig-tools

special-interest-groups/sig-exec/member-list.md
1. AilinKid: 20+ PRs
2. tangenta: 20+ PRs
=> update sig-exec members

special-interest-groups/sig-exec/member-list.md
=> sig-exec: update the member list

special-interest-groups/sig-exec/member-list.md
Propose @pingyu to Reviewers
1. Merged 20+PRs https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Apingyu+is%3Aclosed
2. Improve the performance of `WindowExec` by using multi-thread hash grouping by involving Shuffle executor.https://github.com/pingcap/tidb/pull/14238 
3. support global kill https://github.com/pingcap/tidb/pull/17649 (doing)
=> Propose @pingyu to Reviewers

CONTRIBUTING.md, Hacktoberfest/README.md, README.md, contributors/README.md
This PR:
1. update the contributing guide in the contributor folder
2. remove the contributing guide in the top directory
3. add Hacktoberfest event
=> update contributing guide and hacktoberfest info

Hacktoberfest/README.md
=> hacktoberfest: update info for sig-DDL

special-interest-groups/sig-k8s/member-list.md
Signed-off-by: Song Gao <disxiaofei@163.com>
1. He filed more than 15+ PR
2. He implemented the autoscaling including CRD design / controller logic / unit-test / e2e test which is a hard and large task, and he did it quite well.
=> Propose @howardlau1999 as reviewer of sig-k8s

graduation-proposal/graduation-tidb-dashboard.md
See https://github.com/pingcap/community/issues/332
=> Graduate TiDB Dashboard

architecture/committer-list.md, become-a-committer.md
fix broken link, upload how to become committer and update committer list. Committer list has been moved to new page.
=> upload become a committer and fix broken links

.github/labeler.yml, .github/workflows/ labeler.yml
=> ci: add labeler

special-interest-groups/sig-ddl/membership.json
[coocood](https://github.com/coocood): [20+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Acoocood) of TiDB DDL Component
[jackysp](https://github.com/jackysp): [20+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Ajackysp+label%3Asig%2FDDL+is%3Aclosed) of TiDB DDL Component
=> Promote coocoood and jackysp as committer for ddl sig

special-interest-groups/sig-ddl/membership.json
@morgo has [47 PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Amorgo+is%3Aclosed) merged in TiDB repo and 10+ of them are related to privileges, domain, infoschema.
=> Add @morgo to the 'active contributor' list of sig-DDL.

special-interest-groups/sig-docs/membership.json
- Promote an active contributor: wshwsh12
- Demote 4 active contributors
=> sig-docs: update membership

special-interest-groups/sig-exec/membership.json
Thanks for @xiongjiwei 's contribution!
He has contributed 20+ PRs for sig-exec with 1 medium task:
- PRs: https://github.com/pingcap/tidb/pulls?q=is%3Amerged+is%3Apr+author%3Axiongjiwei+label%3Acomponent%2Fexpression+
- medium task: https://github.com/pingcap/tidb/issues/17596
We propose to promote him to active-contributor.
=> promote @xiongjiwei as active-contributor

special-interest-groups/sig-migrate/README.md
=> sig-migrate: add learning materials and link to issues

special-interest-groups/sig-docs/membership.json
According to [Be promoted to Committer](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-docs/roles-and-organization-management.md#be-promoted-to-committer), we would like to promote @CharLotteiu to a new committer of Docs SIG. Her detailed contribution is shown below:
- Have reviewed 89 PRs in docs-related repos
- Improve docs maintenance efficiency:
- Add conflict mark check in 4 docs repos (https://github.com/pingcap/docs/pull/4026, https://github.com/pingcap/docs-cn/pull/4696, https://github.com/pingcap/docs-dm/pull/438, https://github.com/pingcap/docs-tidb-operator/pull/786)
- Create [a Chrome extension](https://chrome.google.com/webstore/detail/quickswitch/knjplddkmcgipbanhljlbkphpmkhgkfd?hl=zh-CN&authuser=0) to enable quick switch between Chinese and …
=> sig-docs: promote CharLotteiu to committer; promote Joyinqin to reviewer

special-interest-groups/README.md
=> Fix sig goverance link

special-interest-groups/sig-migrate/membership.json
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>
=> Add Wallace to committers

special-interest-groups/sig-k8s/membership.json
@cvvz has submitted [17 PRs](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+author%3Acvvz+is%3Aclosed) and 14 of them have been merged.
=> promote cvvz to reviewer

special-interest-groups/sig-bigdata/README.md, special-interest-groups/sig-bigdata/membership.json, special-interest-groups/sig-bigdata/roles-and-organization-management.md
=> add sig-bigdata

special-interest-groups/sig-sql-infra/README.md
Update the relative path to URL to ensure normal redirection of community website
=> README: update links

special-interest-groups/sig-docs/membership.json
close https://github.com/pingcap/community/issues/406
=> membership: add dragonly as docs's committer

special-interest-groups/sig-docs/README.md
Updated the outdated doc links of the English and Chinese docs to the latest links.
=> updated outdated doc links to new links

special-interest-groups/sig-k8s/membership.json
=> Promote handlerww to committer

special-interest-groups/sig-k8s/membership.json
close https://github.com/pingcap/community/issues/414
=> membership: add dragonly as k8s's committer

special-interest-groups/sig-sql-infra/membership.json
close https://github.com/pingcap/community/issues/421
=> promote Yisaer to reviewer

special-interest-groups/sig-docs/README.md
=> sig-docs: rm links to dbaas-docs

special-interest-groups/sig-exec/membership.json
close https://github.com/pingcap/community/issues/427
=> promote zimulala to sig/exec committer

special-interest-groups/sig-docs/membership.json
close https://github.com/pingcap/community/issues/428
=> membership: add qiancai as docs's active contributor

special-interest-groups/sig-exec/membership.json
close https://github.com/pingcap/community/issues/432
=> membership: add Tjianke as exec's reviewer

special-interest-groups/sig-community-infra/README.md, special-interest-groups/sig-diagnosis/README.md, special-interest-groups/sig-docs/README.md, special-interest-groups/sig-exec/README.md, special-interest-groups/sig-k8s/README.md, special-interest-groups/sig-migrate/README.md, special-interest-groups/sig-planner/README.md, special-interest-groups/sig-sql-infra/README.md, special-interest-groups/sig-tiup/README.md, special-interest-groups/sig-web/README.md
=> fix: refine broken links

special-interest-groups/sig-k8s/membership.json
=> Promote csuzhangxc to committer

special-interest-groups/sig-planner/README.md, special-interest-groups/sig-planner/membership.json
close #423 (two +1 already)
And update the links
=> planner: promote member and update links

special-interest-groups/sig-exec/membership.json
close https://github.com/pingcap/community/issues/437
=> membership: add TszKitLo40 as exec's reviewer

special-interest-groups/sig-docs/membership.json
close https://github.com/pingcap/community/issues/440
=> membership: add qiancai as docs's reviewer

special-interest-groups/sig-k8s/membership.json
=> Promote july2993 to committer

special-interest-groups/sig-docs/membership.json
close https://github.com/pingcap/community/issues/445
=> membership: add qiancai as docs's committer

special-interest-groups/sig-diagnosis/membership.json
close https://github.com/pingcap/community/issues/452
@shhdgit Congrats!
/cc @Mini256 PTAL~ Thanks!
=> membership: add shhdgit as diagnosis's committer

special-interest-groups/sig-community-infra/membership.json
Retire me from leadership and Mini256 will be the new leader to lead the community-infra
=> membership: Retire me from leadership

challenge-programs/challenge-program-season-1.md, contributors/workflow.md, incubator/projects-approval-criteria.md, rfc/2019-12-11-Talent-Plan-Courses.md, special-interest-groups/sig-template/README.md, working-groups/wg-dm-syncer.md
=> fix: refine typos

special-interest-groups/sig-sql-infra/membership.json
close #460 
@Howie59 Congrats!
=> membership: add Howie59 as sql-infra's active contributor

contributors/README.md
=> Update go version in contribution guide

special-interest-groups/sig-exec/membership.json
=> membership: add guo-shaoge as sig-exec's reviewer

special-interest-groups/sig-docs/membership.json
close #465
@dveeden Congrats! 🎉
=> membership: add dveeden as sig-docs's reviewer

GOVERNANCE.md, README.md, contributors/README.md
Add the way to Claim contribution reward in 3 files
=> add the way to claim contribution reward

special-interest-groups/sig-planner/membership.json
=> membership: add zhuo-zhi as sig-planner's reviewer

special-interest-groups/sig-exec/membership.json
=> membership: add ichn-hu as sig-exec's committer

.github/ISSUE_TEMPLATE/sig-promotion.md
Notify operations staff when an issue is created.
=> chore: update the sig promotion assignees

.github/ISSUE_TEMPLATE/sig-promotion.md
=> Revert "chore: update the sig promotion assignees"

special-interest-groups/sig-migrate/membership.json
=> membership: add zwj-coder as sig-migrate's committer

special-interest-groups/sig-migrate/membership.json
=> membership: add Leavrth as sig-migrate's committer

special-interest-groups/sig-docs/membership.json
=> membership: add Liuxiaozhen12 as sig-docs's active contributor

special-interest-groups/sig-migrate/membership.json
=> membership: add gozssky as sig-migrate's reviewer

special-interest-groups/sig-sql-infra/membership.json
=> membership: add tisonkun as sig-sql-infra's active contributor

special-interest-groups/sig-docs/membership.json
=> membership: add Liuxiaozhen12 as sig-docs's reviewer

special-interest-groups/sig-k8s/membership.json
=> membership: add KanShiori as sig-k8s's reviewer

special-interest-groups/sig-exec/membership.json
=> membership: add xhebox as sig-exec's reviewer

special-interest-groups/sig-migrate/membership.json
=> membership: add Ehco1996 as sig-migrate's committer

README.md, communicating.md
Signed-off-by: tison <wander4096@gmail.com>
=> *: update forum as communicating method, and remove legacy approaches

special-interest-groups/sig-migrate/membership.json
=> membership: add hi-rustin as sig-migrate's reviewer

special-interest-groups/sig-docs/membership.json
=> membership: promote Liuxiaozhen12 as sig-docs's committer

special-interest-groups/sig-postgresql/README.md, special-interest-groups/sig-postgresql/membership.json, special-interest-groups/sig-postgresql/roles-and-organization-management.md
add sig-postgresql and initialized the doc
=> add sig-postgresql and initialized the doc

special-interest-groups/sig-sql-infra/membership.json
=> membership: add lcwangchao as sig-sql-infra's reviewer

special-interest-groups/sig-planner/membership.json
=> membership: add xuyifangreeneyes as sig-planner's reviewer

special-interest-groups/sig-migrate/membership.json
=> membership: add asddongmen as sig-migrate's reviewer

special-interest-groups/sig-tiup/membership.json
- Add @nexustar to committers list, he's our new colleague maintaining TiUP.
- Also adjusting member roles
=> update membership of tiup

contributors/README.md
=> contributors: fix help-wanted issues link in readme

toc/proposal/0522-sig-merge.md
Signed-off-by: tison <wander4096@gmail.com>
=> follow ups to #522

teams/kubernetes/README.md
=> teams: fix typo

teams/tidb/README.md
Add a readable TiDB maintainer list to teams/tidb/README.md
=> teams/tidb: Add a readable TiDB maintainer table

teams/tidb/membership.json, votes/0546-tisonkun-as-tidb-reviewer.md
As described in the title, thanks.
=> *: a vote for tisonkun as TiDB reviewer

README.md
close #549, delete tidb-roadmap
=> README.md: delete tidb-roadmap in README.md

teams/tidb/membership.json, votes/0547-andrewdi-as-tidb-reviewer.md
As described in the title, thanks.
=> *: a vote for AndrewDi as the committer

teams/tidb/membership.json, votes/0550-sylzd-as-tidb-reviewer.md
As described in the title, thanks.
=> teams/tidb: a vote for sylzd as the reviewer

teams/migration/membership.json, votes/0555-okJiang-as-migration-reviewer.md
As described in the title, thanks.
=> teams/migration: vote for okJiang as migration reviewer

teams/tidb/membership.json, votes/0557-dveeden-as-tidb-reviewer.md
As stated in the title, thanks.
=> teams/tidb: a vote for dveeden as the reviewer

teams/tidb/membership.json, votes/0561-dveeden-as-tidb-reviewer.md
=> teams/tidb: a vote for dveeden as the reviewer(again)

teams/README.md
Signed-off-by: tison <wander4096@gmail.com>
This closes #565
See also https://github.com/pingcap/community/pull/564#issuecomment-927316414
=> teams: explicitly emphasize maintainers nominate new members

teams/tidb/membership.json, votes/0563-mjonss-as-tidb-reviewer.md
As stated in the title.
Hi @pingcap/tidb-maintainers , PTAL.
=> teams/tidb: a vote for mjonss as the reviewer

teams/README.md
This closes #580 .
cc @LittleFall
@pingcap/tidb-maintainers
=> votes: proposer can have a binding vote

teams/docs/README.md, teams/docs/docs-team-management.md
- Add a `docs-team-management.md` file
- Update docs `README.md` by adding a team management link
=> teams/docs: add docs team management

teams/docs/README.md, teams/docs/docs-team-management.md
- Add one rule for being promoted to Reviewer
- Add one repo https://github.com/pingcap/docs-appdev to the docs repo list
- Update wording
/cc @qiancai @TomShawn
=> teams/docs: update team management

teams/bigdata/README.md, teams/bigdata/membership.json, teams/diagnostic/README.md, teams/diagnostic/membership.json, teams/docs/README.md, teams/docs/membership.json, teams/kubernetes/README.md, teams/kubernetes/membership.json, teams/migration/README.md, teams/migration/membership.json, teams/postgresql/README.md, teams/postgresql/membership.json, teams/tidb/membership.json, teams/tiup/membership.json
=> add description and repos to membership.md

teams/docs/membership.json, votes/0593-hfxsd-as-docs-reviewer.md, votes/hfxsd-as-docs-reviewer.md
As stated in the title.
Hi @pingcap/tidb-maintainers, PTAL.
/hold
=> teams/docs: a vote for hfxsd as the reviewer

votes/0589-time-and-fate-as-tidb-commiter.md
Forget to update the vote results.
=> votes: update the result of #589

teams/kubernetes/membership.json, votes/0598-KanShiori-as-kubernetes-committer.md
=> teams/kubernetes: a vote for KanShiori as the committer

votes/0588-aytrack-as-tidb-reviewer.md
=> teams/tidb: a vote for aytrack as the reviewer

votes/0587-ChenPeng2013-as-tidb-reviewer.md
=> teams/tidb: a vote for ChenPeng2013 as the reviewer

teams/docs/membership.json, votes/0603-en-jin19-as-docs-reviewer.md
As stated in the title.
Hi @pingcap/tidb-maintainers, PTAL.
/hold
=> teams/docs: a vote for en-jin19 as the reviewer

teams/docs/membership.json, votes/0604-shichun-0415-as-docs-reviewer.md
As stated in the title.
Hi @pingcap/tidb-maintainers, PTAL.
/hold
=> teams/docs: a vote for shichun-0415 as the reviewer

teams/docs/membership.json, votes/0602-hfxsd-as-docs-committer.md, votes/hfxsd-as-docs-committer.md
=> teams/docs: a vote for hfxsd as the committer

teams/tidb/membership.json, votes/0607-Defined2014-as-tidb-reviewer.md
=> teams/tidb: a vote for Defined2014 as reviewer

teams/tidb/membership.json, votes/0608-hawkingrei-reviewer.md
=> teams/tidb: a vote for hawkingrei as reviewer

teams/migration/membership.json, votes/0610-hi-rustin-as-migration-commiter.md
=> teams/migration: a vote for hi-rustin as committer

votes/0606-pr-issue-association.md
ref #604 
Co-authored-by: @tisonkun 
Co-authored-by: @Mini256
=> vote for pr issue association rule

contributors/workflow.md
To close https://github.com/pingcap/tidb/issues/29365
=> Remove a shell prompt in contribution guide

teams/docs/membership.json, votes/0615-ngaut-as-docs-reviewer.md, votes/ngaut-as-docs-reviewer.md
=> teams/docs: a vote for ngaut as the reviewer

teams/migration/membership.json, votes/0616-sdojjy-as-migration-reviewer.md
=> teams/migration: a vote for sdojjy as the reviewer

teams/migration/membership.json, teams/tidb/membership.json, votes/0617-joccau-as-tidb-reviewer.md
=> teams/migration: a vote for joccau as the reviewer

teams/migration/README.md, teams/migration/membership.json, votes/0618-asddongmen-as-migration-committer.md
=> teams/migration: a vote for asddongmen as the committer

teams/migration/membership.json, votes/0619-D3Hunter-WizardXiao-as-migration-reviewer.md
=> teams/migration: a vote for D3Hunter and WizardXiao as the reviewer

teams/migration/membership.json, votes/0623-maxshuang-as-migration-reviewer.md
=> teams/migration: a vote for maxshuang as the reviewer

teams/tiup/membership.json, votes/0596-srstack-as-tiup-maintainer.md
Add @srstack to maintainers list, his our new colleague maintaining TiUP.
=> tiup: add srstack to maintainers

teams/tidb/membership.json, votes/0626-zhongzc-as-tidb-reviewer.md
=> votes: add zhongzc as tidb reviewer

teams/tidb/membership.json, votes/0624-guo-shaoge-as-tidb-committer.md
=> votes: add guo-shaoge as tidb committer

teams/bigdata/membership.json, votes/0627-shiyuhang0-as-bigdata-reviewer.md
=> Add shiyuhang0 as BigData reviewer

teams/bigdata/membership.json, votes/0630-xuanyu66-as-bigdata-reviewer.md, votes/0631-xuanyu66-as-bigdata-reviewer.md
=> ADD: A Vote for xuanyu66 as TiBigdata reviewer

teams/migration/membership.json, votes/0620-fengou1-as-tidb-reviewer.md
=> teams/migration: a vote for fengou1 as the reviewer

teams/migration/membership.json, votes/0638-zhaoxinyu-reviewer.md
=> teams/migration: a vote for zhaoxinyu as the reviewer

teams/tidb/membership.json, votes/0636-chrysan-as-tidb-commiter.md
=> *: a vote for chrysan as the TiDB commiter

teams/tidb/membership.json, votes/0640-Defined2014-as-tidb-committer.md, votes/0642-Defined2014-as-tidb-committer.md
=> *: a vote for Defined2014 as the TiDB commiter

teams/tiflash/membership.json
ywqzzy misses the initial tiflash team, add him back.
=> add missing ywqzzy to tiflash team

votes/0645-xuanyu66-as-bigdata-committer.md, votes/0647-xuanyu66-as-bigdata-committer.md
Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>
=> Nominate xuanyu66 as BigData committer

votes/0648-shiyuhang0-as-bigdata-committer.md
Signed-off-by: Xiaoguang Sun <sunxiaoguang@gmail.com>
=> Nominate shiyuhang0 as BigData committer

teams/migration/membership.json, votes/0650-CharlesCheung96-as-migration-reviewer.md
=> teams/migration: a vote for CharlesCheung96 as reviewer

teams/migration/membership.json, votes/0653-buchuitoudegou-as-migration-reviewer.md
=> teams/migration: a vote for buchuitoudegou as migration reviewer

teams/migration/membership.json, votes/0654-niubell-as-migration-reviewer.md
=> teams/migration: a vote for niubell as migration reviewer

teams/tidb/membership.json, votes/0655-mornyx-as-tidb-reviewer.md
@mornyx has been [working for](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Amornyx+is%3Aclosed) the Top SQL feature of TiDB for several months, revealed sufficient capability.
=> teams/tidb: a vote for mornyx as tidb reviewer

teams/migration/membership.json, votes/0651-D3Hunter-as-migration-committer.md
=> teams/migration: a vote for D3Hunter as migration committer

teams/tidb/membership.json, votes/0659-joccau-as-tidb-committer.md
=> teams/tidb: a vote for joccau as tidb committer

archive/governance/special-interest-groups/sig-diagnosis/membership.json, archive/governance/special-interest-groups/sig-docs/membership.json, archive/governance/special-interest-groups/sig-exec/membership.json, archive/governance/special-interest-groups/sig-tiup/membership.json, archive/governance/working-groups/wg-tracing.md, teams/diagnostic/membership.json, teams/docs/membership.json, teams/tidb/README.md, teams/tidb/membership.json, teams/tiflash/membership.json, teams/tiup/membership.json, votes/0592-tisonkun-as-tidb-committer.md, votes/0655-mornyx-as-tidb-reviewer.md
Signed-off-by: Wish <breezewish@outlook.com>
Recently I updated my github username from breeswish to breezewish. This PR updates the username list.
=> *: change for breezewish rename

teams/tidb/membership.json, votes/0661-zanmato1984-as-tidb-committer.md
=> promote zanmato1984 as committer

teams/migration/membership.json, votes/0665-sdojjy-as-migration-committer.md
=> teams/migration: a vote for sdojjy as migration committer

teams/tiunimanager/membership.json
Update committers and reviewers
=> teams/tiunimanager: update membership

contributors/README.md
=> update TiDB CLA link

teams/tidb/membership.json, votes/0703-zyguan-as-tidb-committer.md
As the title said.
@cfzjywxk @sticnarf PTAL
cc @zyguan
=> team/tidb: a vote for zyguan as the committer

teams/bigdata/membership.json
=> add missing bigdata entry

teams/tidb/membership.json, votes/0713-Benjamin2037-as-tidb-reviewer.md
=> teams/tidb: a vote for Benjamin2037 as TiDB reviewer

teams/docs/membership.json, votes/0714-Icemap-as-docs-reviewer.md
=> teams/docs: a vote for Icemap as the reviewer

teams/tidb/membership.json, votes/0716-TonsnakeLin-as-tidb-reviewer.md
See the [vote doc](https://github.com/you06/community/blob/TonsnakeLin-reviewer/votes/0716-TonsnakeLin-as-tidb-reviewer.md).
=> teams/tidb: a vote for 'TonsnakeLin' as the reviewer

teams/docs/membership.json, votes/KanShiori-as-docs-reviewer.md
=> teams/docs: a vote for KanShiori as a reviewer

teams/tidb/membership.json, votes/0723-mengxin9014-as-tidb-reviewer.md
=> team/tidb: a vote for mengxin9014 as the reviewer

votes/1117-Benjamin2037-as-tidb-committer.md
Signed-off-by: Jack Yu <jackysp@gmail.com>
As title says.
=> teams/tidb: a vote for Benjamin2037 as TiDB committer

teams/tidb/membership.json, votes/0728-BornChanger-as-tidb-reviewer.md
=> teams/tidb: a vote for BornChanger as TiDB reviewer

teams/migration/membership.json, votes/0732-CharlesCheung96-as-migration-comitter.md
=> teams/migration: a vote for CharlesCheung96 as the committer

teams/migration/membership.json, votes/0735-MoCuishle28-as-migration-reviewer.md
=> vote: promote MoCuishle28 as tidb reviewer

toc/README.md, votes/0743-tiancaiamao-as-toc-member.md
Nominate tiancaiamao as TOC Member
Closes: #743
=> Nominate tiancaiamao as TOC member

toc/README.md, votes/0741-coocood-as-toc-member.md
I ([@sunxiaoguang](https://github.com/sunxiaoguang)) thereby nominate [@coocood](https://github.com/coocood) as TOC member and call for a vote.
Closes: #741
=> Nominate coocood as TOC Member

teams/tidb/membership.json, votes/0737-3pointer-as-tidb-maintainer.md, votes/xxxx-3pointer-as-tidb-maintainer.md
=> vote: promote 3pointer as tidb maintainer

teams/tidb/membership.json, votes/0750-glorv-as-tidb-maintainer.md
=> teams/tidb: a vote for glorv to TiDB maintainer

teams/tidb/membership.json, votes/0756-yangkeao-as-tidb-committer.md
=>  teams/tidb: a vote for yangkeao as TiDB commiter

teams/tidb/membership.json, votes/0762-elsa0520-as-tidb-reviewer.md, votes/elsa0520-as-tidb-reviewer.md
=> team/tidb: a vote for elsa0520 as TiDB reviewer

teams/diagnostic/membership.json
- Add `mornyx` as committer @mornyx
- Change `shhdgit` from committer to maintainer @shhdgit
=> Update membership.json for tidb-dashboard repo

teams/diagnostic/membership.json
=> Revert "Update membership.json for tidb-dashboard repo"

README.md
Add a new community channel - Discord
=> README: Add discord channel

teams/tidb/membership.json, votes/0772-jiyfhust-tidb-reviewer.md
=> votes: a vote for jiyfhust as the reviewer 

teams/tidb/membership.json, votes/0775-lyzx2001-as-tidb-reviewer.md
=> Vote lyzx2001 as TiDB reviewer.

teams/tidb/membership.json, votes/0778-ywqzzy-as-tidb-committer.md
=> teams/tidb: a vote for ywqzzy as TiDB commiter

teams/migration/membership.json
=> teams/migration: vote hongyunyan as migration team committer

teams/tidb/membership.json, votes/0783-BrianZhang-as-tidb-committer.md, votes/0784-BrianZhang-as-tidb-committer.md
=> Vote for BornChanger for TiDB committer.

teams/tidb/membership.json, votes/0786-yibin87-as-tidb-reviewer.md
=> nominate yibin87 as tidb reviewer

teams/tiflash/OWNERS, teams/tiflash/membership.json, votes/0787-windtalker-as-tiflash-maintainer.md
See the content of the included vote file.
=> Vote: Nominate windtalker as TiFlash maintainer

contributors/README.md
Add Discord to go along with Slack.
=> Update README.md to add the Discord link

teams/tidb/membership.json, votes/0806-joechenrh-as-tidb-reviewer.md
=> team/tidb: joechenrh-as-tidb-reviewer

teams/ticdc/membership.json
I(@tenfyzhong) have contributed to TiCDC repository in the past half year. 
the following lists the details of my contributions:
- [authored pull requests](https://github.com/pingcap/ticdc/pulls?q=is%3Apr+is%3Amerged+author%3Atenfyzhong+)
- [authored issues](https://github.com/pingcap/ticdc/issues?q=is%3Aissue%20author%3Atenfyzhong)
I nominate myself @tenfyzhong as a TiCDC committer and call for a vote
=> team/ticdc: A vote for nomination of tenfyzhong as the TiCDC committer
