pingcap/community

code-comment-style.md

Because the official capitalization of "Kubernetes" is changed sometimes, I remove this example.
@dcalvin Please also update this part in the tikv repo. Thanks.

Remove the capitalization example of "k8s"

---

CONTRIBUTING.md

Seems for me only 1.13 works. 
Using 1.12 give me error:
```
make
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes -trimpath  -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v2.1.0-beta-2471-g875873b" -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=2019-10-29 06:41:30" -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=875873b7ca4267c0bbb2e4fe31c1561dea3f495d" -X "github.com/pingcap/tidb/util/printer.TiDBGitBranch=master" -X "github.com/pingcap/tidb/util/printer.GoVersion=go version go1.12 darwin/amd64" ' -o bin/tidb-server tidb-server/main.go
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [server] Error 2
```

Update CONTRIBUTING.md go version

---

rfc/2019-11-28-discourse-on-tidb.md
rfc/README.md

Signed-off-by: sykp241095@gmail.com
This is a proposal about migration of Discourse's database from PostgreSQL to MySQL.
1. Eat our own dog food before release;
2. This migration is a big event in both TiDB community and Discourse(Rails) Community;

proposal: run Discourse on TiDB

---

working-groups/README.md
working-groups/wg-tidb-sequence.md

Add working group of Sequence.

add working group of sequence

---

contributors/README.md

Update the link to the page `active working groups`.

Fix: update dead link in contributors document

---

working-groups/README.md
working-groups/wg-stmt-summary.md

Add a new working group `wg-stmt-summary`. This working group is intended to discuss details of statement summary tables in TiDB.

working-groups: add description for `wg-stmt-summary`

---

rfc/2020-02-24-cherry-bot.md

This is a proposal about Cherry Bot.
* Launch of incubation project on Cherry Bot
* Develop and share the bot with community

rfc: add cherry bot as incubator program

---

special-interest-groups/sig-ddl/member-list.md
special-interest-groups/sig-exec/member-list.md
special-interest-groups/sig-planner/member-list.md

Actually we don't have co-leads, this PR removes the description for co-leads

SIG: remove co-leads

---

special-interest-groups/sig-docs/README.md

Update the normal link of joining #sig-docs Slack channel.

sig: update #sig-docs slack link

---

special-interest-groups/sig-docs/member-list.md

Promote @zhouqiang-cl to an active contributor in light of his contribution to the docs refactoring.

sig-docs: promote a contributor to active contributor

---

special-interest-groups/sig-planner/member-list.md

add members according to the https://github.com/pingcap/community/blob/master/special-interest-groups/sig-planner/roles-and-organization-management.md

sig: add memebers for sig-planner

---

special-interest-groups/README.md

Signed-off-by: wuxuelian <AndreMouche@126.com>		
Hi, This PR  update the README docs with the following items:
- active sigs
- information about sig governance
- information about how to contribute in sig

sepical_interest_group/readme: update active sigs and add more information for sigs and how to contribute

---

special-interest-groups/sig-exec/member-list.md

Add these committers:
1. crazycs520: contribute 98 PRs about exec and add the memory table `slow-query` for TiDB;
2. tiancaiamao: contribute 82 PRs about exec and implement partition tables for TiDB;
3. jackysp: contribute 62 PRs about exec;
4. lysu: contribute 59 PRs about exec and implement the `prepare-stmt` for TiDB;
5. coocood: design and implement clustered index for TiDB;

sig: update the sig-exec member list

---

working-groups/README.md
working-groups/wg-tracing.md

This PR creates a new working group: Timeline Tracing Working Group (wg-tracing).

Add wg-tracing working group

---

special-interest-groups/sig-dashboard/README.md
special-interest-groups/sig-dashboard/member-list.md
special-interest-groups/sig-dashboard/roles-and-organization-management.md

Previously there are some misunderstandings when adding PingCAP members to the member list. Now I refined the member list and their roles according to the charter.

Update member list of sig-dashboard

---

special-interest-groups/sig-planner/member-list.md

XuHuaiyu and qw4990 did many works to make the optimizer stable and correct.
So I suggest promote them as committer.

sig-planner: promote XuHuaiyu and qw4990 to committer

---

special-interest-groups/sig-scheduling/member-list.md

[JmPotato](https://github.com/JmPotato) has contributed [10](https://github.com/pingcap/pd/pulls?q=is%3Apr+is%3Aclosed+author%3AJmPotato) PRs. This PR is going to promote him to be an active contributor.

sig-scheduling: promote JmPotato to the active contributor

---

special-interest-groups/sig-k8s/member-list.md

@mikechengwei has done great work in tidb-operator development. List of contributions: https://github.com/pingcap/tidb-operator/pulls/mikechengwei 
We've decided to promote him to the reviewer of sig-k8s!

sig-k8s: Promote Mike to reviewer

---

special-interest-groups/sig-planner/member-list.md

SunRunAway: Fix more than 30 bugs and support distinct aggregation push down in planner, so I promote him to committer formally.

sig-planner: promote SunRunAway to committer

---

special-interest-groups/sig-ddl/member-list.md

The following is the number of PR that contributors have been merged:
xhebox merged 21 PRs
xiongjiwei merged 11 PRs
wangggong merged 10 PRs

*: update SIG-DDL member-list

---

special-interest-groups/sig-tiup/member-list.md

This contributor has contribute [13 PRs](https://github.com/pingcap/tiup/pulls?q=is%3Apr+author%3A9547) (11 merged) for [TiUP repo](https://github.com/pingcap/tiup). It's time to promote him as an active contributor.

Promote 9547 as active contributor of TiUP

---

special-interest-groups/sig-k8s/member-list.md

@july2993 is the core team member of tidb-operator, see contributions: https://github.com/pingcap/tidb-operator/commits?author=july2993

sig-operator: Promote july2993 as reviewer

---

special-interest-groups/sig-k8s/member-list.md

@shonge is an active contributor of sig-k8s and contributed almost 30 PRs (25 merged). I promote him as our reviwer and participart code-review. see contributions: https://github.com/pingcap/tidb-operator/commits?author=shonge

sig-k8s: Promote shonge as reviewer

---

special-interest-groups/sig-ddl/member-list.md

As stated:
@xiongjiwei has [20+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Axiongjiwei+is%3Aclosed) merged in TiDB repo related to DDL and charset, in which:
- Finished the development of https://github.com/pingcap/tidb/issues/17596 (a valuable and difficult work)
- Fixed some major bugs of TiDB, such as: #18665, #19189 #19166

update member list for sig/ddl, promote xiongjiwei to reviewer

---

special-interest-groups/sig-exec/member-list.md

1. He filed more than 30+ PRs
2. He implemented the copr-cache feature which is a hard issue.

Propose @breeswish as reviewer of sig-exec

---

special-interest-groups/sig-ddl/member-list.md

For the past months, @xhebox is very active in contributing to the TiDB project, his jobs included:
- [20+ merged PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Axhebox+is%3Aclosed) in TiDB repo and [11 merged PRs](https://github.com/pingcap/parser/pulls?q=is%3Apr+author%3Axhebox+is%3Aclosed) in parser repo.
- Closed https://github.com/pingcap/tidb/issues/18756 and https://github.com/pingcap/tidb/issues/19122 that are medium-difficulty issue.
- Finished the development of https://github.com/pingcap/tidb/issues/18030 (AKA the 'geo partition'), which is an important feature of the next version of TiDB.
- Reviewd [10+ PRs](https://github.com/search?q=is%3Apr+reviewed-by%3Axhebox+updated%3A%3E%3D2020-01-01+-author%3Axhebox) since he've been promoted as the reviewer of TiDB …

update memberlist for sig-DDL, promote xhebox as the commiter.

---

special-interest-groups/sig-migrate/member-list.md

According to stats,
1. Promote `@qinggniq` to Active Contributor
2. Remove `@ericsyh` from Active Contributor
3. Update list of contributors.

sig-migrate: update member list

---

special-interest-groups/sig-docs/README.md

- Add TiDB Cloud and the dbaas-docs repo to the list
- Update two old links to docs.pingcap.com links

sig-docs: update intro to Docs SIG

---

special-interest-groups/sig-docs/membership.json

According to [Be promoted to Reviewer](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-docs/roles-and-organization-management.md#be-promoted-to-reviewer), we would like to promote @CharLotteiu to a new reviewer of Docs SIG. Her detailed contribution is shown below:
- Have 37 PRs merged in documentation repositories within one year
- Improve docs maintenance efficiency:
- Add conflict mark check in 4 docs repos (https://github.com/pingcap/docs/pull/4026, https://github.com/pingcap/docs-cn/pull/4696, https://github.com/pingcap/docs-dm/pull/438, https://github.com/pingcap/docs-tidb-operator/pull/786)
- Create [a Chrome extension](https://chrome.google.com/webstore/detail/quickswitch/knjplddkmcgipbanhljlbkphpmkhgkfd?hl=zh-C …

sig-docs: promote Charlotteiu to reviewer

---

special-interest-groups/sig-tiup/membership.json

This active contributor has contributed [28 PRs](https://github.com/pingcap/tiup/pulls?q=is%3Apr+author%3A9547) (25 merged) for [TiUP repo](https://github.com/pingcap/tiup). It's time to promote him as a reviewer.

Promote 9547 as a reviewer of TiUP

---

special-interest-groups/sig-exec/membership.json

Since @Yisaer has contributed a lot to sig-exec, according to sig-exec [roles-and-organization-management.md#promotion](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-exec/roles-and-organization-management.md#from-reviewer-to-committer), we would like to promote him to our new committer, and his detailed contribution is shown below:
1. contribute [20+](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Ayisaer+label%3Astatus%2Fcan-merge+label%3Asig%2Fexecution) PRs to the executor,
2. support the [global memory tracker](https://github.com/pingcap/tidb/pull/16777) (a medium task)
4. support the ratelimit action to solve the [table reader oom problem](https://github.com/pingcap/tidb/issues/16104) (a hard task)
5. help other contributors and review …

Propose @Yisaer as committer of sig-exec

---

special-interest-groups/sig-k8s/membership.json

@mikechengwei has almost 30 [PRs](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+author%3Amikechengwei+is%3Aclosed) merged in the tidb-operator repo, 3 [PRs](https://github.com/pingcap/docs-tidb-operator/pulls?q=is%3Apr+author%3Amikechengwei+is%3Aclosed) merged in the docs-tidb-operator repo, and finishes the below big features by himself:
- Heterogeneous cluster deployment https://github.com/pingcap/tidb-operator/issues/2240
- Migrate the deployment of TidbMonitor from deployment to statefulset https://github.com/pingcap/tidb-operator/pull/3440

promote mikechengwei as committer of tidb-operator

---

special-interest-groups/sig-ddl/membership.json

Since @xiongjiwei  has contributed a lot to sig-ddl, according to sig-ddl [roles-and-organization-management.md](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-ddl/roles-and-organization-management.md#promotion), we would like to promote him to our new committer, and his detailed contribution is shown below:
1.  Contribute [20+](https://github.com/pingcap/tidb/pulls?q=is%3Apr+label%3Asig%2FDDL+author%3Axiongjiwei+is%3Aclosed) PRs to the DDL sig.
2. Review [10+](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Axiongjiwei+-author%3Axiongjiwei) PRs.
3. Implement unicode-ci in both TiDB and TiKV.

Promote xiongjiwei as the committer for DDL sig

---

special-interest-groups/sig-ddl/membership.json

@blacktear23 is very active in the past few months, his contributions
includes:
- [14 merged
PRs](https://github.com/pingcap/parser/pulls?q=is%3Apr+author%3Ablacktear23+is%3Aclosed) in TiDB repo and 10 of them are
DDL-related
- [2 merged PRs](https://github.com/pingcap/parser/pulls?q=is%3Apr+author%3Ablacktear23+is%3Aclosed) in parser
repo

sig-ddl: promote 'blacktear23' to active contributor

---

special-interest-groups/sig-exec/membership.json

Since @wjhuang2016 has contributed a lot to sig-exec, according to sig-exec [roles-and-organization-management.md#promotion](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-exec/roles-and-organization-management.md#from-reviewer-to-committer), we would like to promote him to our new committer, and his detailed contribution is shown below:
contribute [30 PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Awjhuang2016+label%3Asig%2Fexecution) to the executor,
support the [expression index](https://github.com/pingcap/tidb/issues/18008) (a medium task)
support the [new collation](https://github.com/pingcap/tidb/issues/14573) (a hard task)
help other contributors and review [150+](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Awjhuang2016+-a …

Propose @wjhuang2016 as committer of sig-exec

---

special-interest-groups/sig-k8s/membership.json

@handlerww has submitted 11 [PRs](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+is%3Aclosed+author%3Ahandlerww) to the tidb-operator repo.
@dragonly has submitted 13 [PRs](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+is%3Aclosed+author%3Adragonly) to the tidb-operator repo.
Although @csuzhangxc only submitted one PR he is a very experienced engineer and has contributed a lot of PRs to the other repo, such as dm repo.

promote new reviewers for sig-k8s

---

.github/labeler.yml
special-interest-groups/README.md
special-interest-groups/sig-community-infra/README.md
special-interest-groups/sig-community-infra/membership.json
special-interest-groups/sig-community-infra/roles-and-organization-management.md

The community needs some infrastructure tools to enhance the community experience, and we have been working on this part of the infrastructure tools for some time, so we hope to set up a sig to work with the community to maintain and update these infrastructure tools.

sig: Add community-infra sig and submit relevant information

---

special-interest-groups/sig-planner/membership.json

Promote three reviewer
Both of them contributes many codes for planner-sig.
And designed thing such as new statistics for sampling based data, and the index usage table.

sig-planner: add reviewers

---

special-interest-groups/sig-docs/membership.json

Promote 3 contributors to active contributors.

sig-docs: promote 3 active contributors

---

special-interest-groups/sig-migrate/membership.json

I (@liuzix) now satisfy the requirements for being promoted to a commiter.
Requirements
- Have at least 30 PRs merged within one year (Yes, 34 PRs in TiCDC)
- Have reviewed at least 20 PRs within one year. (Yes, at least 25 in TiCDC)
- Nominated by at least 2 Committers or Maintainers. (@leoppro @amyangfei PTAL)

Promote liuzix to committer

---

special-interest-groups/sig-tiup/membership.json

This reviewer has contributed [45 PRs](https://github.com/pingcap/tiup/pulls?q=is%3Apr+author%3A9547) (42 merged) for [TiUP repo](https://github.com/pingcap/tiup). It's time to promote him as a committer.

Promote 9547 as a committer of TiUP

---

special-interest-groups/sig-diagnosis/membership.json

Promote iosmanthus and zhongzc to committer.
iosmanthus's contributions: https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Aiosmanthus
zhongzc's contributions: Timeline Tracing

Update membership for sig-diagnosis

---

special-interest-groups/sig-sql-infra/membership.json

@morgo now satisfies the requirements for being promoted to a committer.
Requirements

promote morgo to committer

---

special-interest-groups/sig-docs/membership.json

According to [Be promoted to Reviewer](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-docs/roles-and-organization-management.md#be-promoted-to-reviewer), we would like to promote @dragonly to a new reviewer of Docs SIG. His detailed contribution is shown below:
- Have [merged 20 PRs](https://github.com/pingcap/docs-tidb-operator/pulls?q=is%3Apr+author%3Adragonly) in the docs-tidb-operator repo.
- Have [addressed 2 issues](https://github.com/pingcap/docs-tidb-operator/issues?q=is%3Aissue+assignee%3Adragonly+is%3Aclosed).
- Have a general command of technical writing and documentation rules. See [one of his pull requests](https://github.com/pingcap/docs-tidb-operator/pull/952).
This PR also includes the promotion of 3 …

sig-docs: update membership

---

special-interest-groups/sig-bigdata/README.md
special-interest-groups/sig-community-infra/README.md
special-interest-groups/sig-diagnosis/README.md
special-interest-groups/sig-docs/README.md
special-interest-groups/sig-exec/README.md
special-interest-groups/sig-k8s/README.md
special-interest-groups/sig-migrate/README.md
special-interest-groups/sig-planner/README.md
special-interest-groups/sig-tiup/README.md
special-interest-groups/sig-web/README.md

In https://developer.tidb.io/sig, the links to Roles and Organization Management are broken. 
For example, if you click  **Docs SIG Roles and Organization Management** in https://developer.tidb.io/sig/docs, you will get the 404 error. 
This PR changes the relative paths to the actual paths to fix the broken links.

Fixed the broken links to Roles and Organization Management for SIGs

---

contributors/README.md

It should be `GitHub` and we don't need to add the parameter.

fix: refine typo

---

special-interest-groups/README.md

TiKV has its own community and no longer consists in SIGs. See also [GOVERNANCE](https://github.com/tikv/community/blob/master/GOVERNANCE.md) for how it constructs now.

Remove TiKV SIGs

---

teams/tidb/membership.json
votes/0544-sig-txn-reviewer-to-tidb.md

Add reviewers from the sig-transaction to the TiDB team: @ekexium, @longfangsong, @you06, which is missing in #522

Add sig-transaction's reviewers

---

teams/tidb/membership.json

The wrong JSON format caused an error in the program that synchronizes membership data, fix it.
Maybe we should introduce a CI(Github Actions) to verify the format.

fix: fix typo in tidb membership.json

---

teams/README.md

I'd like to propose three new details for our governance model.
1. reviewer could be nominated by committers, hope to reduce maintainers' work and find more reviewers
2. roles are not exchangeable between teams. currently, docs team has their own management rule https://github.com/pingcap/community/blob/master/teams/docs/docs-team-management.md different with other teams, a tidb committer may not be a qualified docs reviewer/committer/maintainer.
3. although each team might has its own rules, but teams are also highly connected. a contributor may participate in several teams at the same time, so I think if a contributor has been one team's member, allowing him/her to nominate him/herself for another team could reduce unnecessary communication. Of course, the nomination needs to be …

disallow exchanging roles between teams

---

teams/tidb/membership.json

This is not a vote. AndreMouche has the priviledges before but during migration seems it's lost. Her contributions could been checked: https://github.com/pingcap/tidb/pulls?q=is%3Apr+AndreMouche+is%3Aclosed

add AndreMouche as committer

---

teams/tiflash/README.md
teams/tiflash/membership.json

TiFlash is open source on April 1st. It should follow the governance model of TiDB community now. This PR establish the new TiFlash team and its initial team members.
After merge of this PR, I'll create corresponding GitHub team and @Mini256 would change the bot configuration. Previous members of TiFlash repo would be removed. cc @luzizhuo

add tiflash team

---

teams/tidb/membership.json
votes/0666-cbcwestwolf-as-tidb-committer.md

[@cbcwestwolf](https://github.com/cbcwestwolf) has been working on `pingcap/tidb` for several months, he has made contributions to variety of the components of TiDB(sysvar, expression, config, etc). The details of his contributions are listed as follows:
* [Authored pull requests](https://github.com/pingcap/tidb/issues?q=is%3Apr+author%3Acbcwestwolf+is%3Aclosed)
* [Reviewed pull requests](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Acbcwestwolf+)
I (@tangenta) hereby nominate @cbcwestwolf as TiDB Reviewer and call for a vote.

teams/tidb: a vote for cbcwestwolf as tidb reviewer

---

teams/bigdata/membership.json
votes/0666-Daemonxiao-as-bigdata-reviewer

I hereby nominate [@Daemonxiao](https://github.com/Daemonxiao) as bigdata reviewer. He has been working on `pingcap/tispark` for several months, he has implemented telemetry feature and TLS feature. The details of his contributions are listed as follow:
* Authored pull requests
* [TiSpark](https://github.com/pingcap/tispark/commits?author=Daemonxiao)
* Reviewed pull requests
* [TiSpark](https://github.com/pingcap/tispark/pulls?q=is%3Apr+reviewed-by%3ADaemonxiao)
* [TiBigData](https://github.com/tidb-incubator/TiBigData/pulls?q=is%3Apr+reviewed-by%3ADaemonxiao)

team/bigdata: a vote for Daemonxiao as bigdata reviewer

---

votes/0677-zhangyangyu-reviewer.md

I hereby nominate [@zhangyangyu ](https://github.com/zhangyangyu) as BigData reviewer. He has been reviewing PRs on `pingcap/tispark` and `tidb-incubator/TiBigData` for several months and contributed many valuable insights to other contributors. The details of his contributions are listed as follow:
* Reviewed pull requests
* [TiSpark](https://github.com/pingcap/tispark/pulls?q=is%3Apr+reviewed-by%3Azhangyangyu)
* [TiBigData](https://github.com/tidb-incubator/TiBigData/pulls?q=is%3Apr+reviewed-by%3Azhangyangyu)

A Vote for zhangyangyu as BigData reviewer

---

teams/tiflash/membership.json
votes/697-hongyunyan-as-tiflash-committer.md

During the few months, [@hongyunyan](https://github.com/hongyunyan) has focused on the development of TiFlash.  She has posted [12 PRs](https://github.com/pingcap/tiflash/pulls/hongyunyan) and 10 PRs merged. She is very familiar with the DDL module of TiFlash and made a sharing about DDL's code review.
I (@flowbehappy) hereby nominate @hongyunyan as TiFlash committer and call for a vote.
The vote will be open for at least 6 days unless there is an objection or not enough votes.
* TiFlash

teams/tiflash: a vote for hongyunyan as a committer 

---

toc/README.md

Update affiliation of TOC member @baiyuqing and @niubell to reflect the most recent status.

Update TOC affiliation for baiyuqing and niubell

---

toc/README.md
votes/0745-winkyao-as-toc-member.md

I ([@sunxiaoguang](https://github.com/sunxiaoguang)) thereby nominate [@winkyao](https://github.com/winkyao) as TOC member and call for a vote.
Closes #745

Nominate winkyao as TOC member

---

toc/README.md

change TOC member's affiliation from company to project, to keep consistent with the others.

toc: change affiliation from company to project

---

teams/docs/docs-team-management.md

Remove the outdated information of the "Quit and demotion" section.

teams/docs: remove outdated info

---

teams/tidb/membership.json

In https://github.com/pingcap/community/pull/726, I forgot to change the `membership.json` for Benjamin2037. Now I want to add him back.

teams/tidb: fix missing change

---

teams/tidb/membership.json
votes/0778-xzhangxian1008-as-tidb-reviewer.md
votes/0779-xzhangxian1008-as-tidb-reviewer.md

promote xzhangxian1008 as TiDB reviewer

---

teams/docs/membership.json
votes/0780-Icemap-as-docs-committer.md

teams/docs: a vote for Icemap as the committer

---

teams/migration/membership.json
votes/0782-lidezhu-as-migration-committer.md

[lidezhu](https://github.com/lidezhu) have contributed a lot to TiFlow repo, he has fixed several issues and has been doing some enhancement work in TiCDC.
I (@asddongmen) hereby nominate @lidezhu as migration committer and call for a vote.
The vote will be open for at least 6 days unless there is an objection or not enough votes.
* Team Migration
See also [here](https://github.com/pingcap/community/pull/782).

a vote for lidezhu as a committer

---

teams/migration/membership.json
votes/0783-zhangjinpeng87-as-migration-committer.md

[@zhangjinpeng87](https://github.com/zhangjinpeng87) is the head of TiDB Data Platform team. He has focused on the system architecture and further iteration of data migration, and contributed greatly to improving the stability and observability of TiCDC.
Here lists the details of his contribution:
* [Authored pull requests in TiFlow](https://github.com/pingcap/tiflow/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+author%3Azhangjinpeng87)
* [Authored issues in TiFlow](https://github.com/pingcap/tiflow/issues?q=is%3Aissue+author%3Azhangjinpeng87)
I (@CharlesCheung96) hereby nominate @zhangjinpeng87 as migration committer and call for a vote for the following reasons:
* Deep contributions on TiCDC.
* Reviewed and commented many important issues and PRs.
The vote will be open for at least 6 …

teams/migration: A Vote for zhangjinpeng87 as Migration Committer

---

teams/migration/membership.json
votes/0789-wk989898-as-migration-committer.md

[@wk989898](https://github.com/wk989898)  have contributed a lot to TiFlow repo, he has fixed several issues and added several core features in TiCDC, including Kafka consumer enhancement and vector type support, etc.
Here lists the details of his contribution:
* [Authored pull requests in TiFlow](https://github.com/pingcap/tiflow/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+author%3Awk989898)
* [Authored issues in TiFlow](https://github.com/pingcap/tiflow/issues?q=is%3Aissue+author%3Awk989898)
I (@CharlesCheung96) hereby nominate @wk989898 as migration committer and call for a vote for the following reasons:
* Deep contributions on TiCDC.
* Reviewed and commented many important issues and PRs.
The vote will be open for at least 6 days unless there is an objection or not enough votes. …

teams/migration: A Vote for wk989898 as Migration Committer

---

teams/docs/docs-team-management.md
teams/docs/membership.json

- Adds the "Emeritus approvers" section to [teams/docs/docs-team-management.md](https://github.com/pingcap/community/blob/master/teams/docs/docs-team-management.md)
- Moves inactive contributors from "committers" to "emeritus_approvers" in [teams/docs/membership.json](https://github.com/pingcap/community/blob/master/teams/docs/membership.json)
- Removes two GitHub IDs from the "maintainers" list because they already exist in the "emeritus_approvers" list
Reference: https://github.com/pingcap/docs/pull/19599

Add emeritus approvers to docs

---

teams/ticdc/OWNERS
teams/ticdc/README.md
teams/ticdc/membership.json

This PR adds a new `teams/ticdc` folder under the `pingcap/community` repository to manage and organize the TiCDC community.
As TiCDC evolves with its new architecture, having a dedicated folder will help improve community collaboration by:
* Defining roles, responsibilities, and governance for the TiCDC team.
* Centralizing TiCDC-related community activities.
The structure and contents of the folder align with existing teams folders in this repository, ensuring consistency across projects.

teams/ticdc: add teams/ticdc folder for managing TiCDC community

---

teams/migration/membership.json
votes/0792-wlwilliamx-as-migration-committer.md

[@wlwilliamx](https://github.com/wlwilliamx) has been working on `pingcap/tiflow` and `pingcap/ticdc` for more than six months. He contributes mainly to addressing compatibility challenges related to DDL synchronization, and enhancing the security, stability and observability of TiCDC project.
Here lists the details of his contribution:
* [Authored pull requests in TiCDC](https://github.com/pingcap/ticdc/pulls?q=is:pr+sort:updated-desc+is:closed+author:wlwilliamx+)
* [Authored issues in TiCDC](https://github.com/pingcap/ticdc/issues?q=is:issue+author:wlwilliamx)
* [Authored pull requests in TiFlow](https://github.com/pingcap/tiflow/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+author%3Awlwilliamx+)
* [Authored issues in TiFlow](https://github.com/pingcap/tiflow/issues?q=is%3Aissue+author …

A Vote for wlwilliamx as Migration Committer

---

teams/kubernetes/OWNERS
teams/kubernetes/membership.json

[fgksgf](https://github.com/fgksgf) has many contributions on [TiDB Operator v2](https://github.com/pingcap/tidb-operator/tree/v2)

teams/kubernetes: A Vote for fgksgf as the committer
